destination_frame: base_link
cloud_destination_topic: merged_clouds
scan_destination_topic: merged_scan
angle_min: -3.13
angle_man: 3.13
angle_increment: 0.0058
scan_time: 0.02
range_min: 0.5
range_max: 25
