global_costmap:
  robot_radius: 0.7
  update_frequency: 1.25055
  publish_frequency: 1.0
  transform_tolerance: 0.2033
  track_unknown_space: true
  rolling_window: false
  always_send_full_costmap: false
  trinary_costmap: true
  resolution: 0.1
  plugins:
    - name: planner_map_layer
      type: costmap_2d::StaticLayer
    - name: obstacles_layer
      type: costmap_2d::ObstacleLayer
    - name: inflation_layer
      type: costmap_2d::InflationLayer
