local_costmap:
  global_frame: map
  robot_base_frame: base_link
  footprint: [[-0.4, -0.185], [-0.4, 0.185], [0.4, 0.185], [0.4, -0.185]]
  update_frequency: 3.0505
  publish_frequency: 1.0
  transform_tolerance: 0.20111
  track_unknown_space: false
  rolling_window: true
  width: 10.5
  height: 10.5
  resolution: 0.15
  always_send_full_costmap: false
  plugins:
    - name: obstacles_layer
      type: costmap_2d::ObstacleLayer
    - name: inflation_layer
      type: costmap_2d::InflationLayer
