shutdown_costmaps: false
conservative_reset_dist: 3.0

base_global_planner: carrot_planner/CarrotPlanner
base_global_planner: navfn/NavfnROS
base_global_planner: global_planner/GlobalPlanner

planner_frequency: 0.088888
planner_patience: 5.088888

oscillation_distance: 0.1
oscillation_timeout: 10.0

base_local_planner: base_local_planner/TrajectoryPlannerROS
base_local_planner: dwa_local_planner/DWAPlannerROS

controller_frequency: 9.502222
controller_patience: 10.022222

max_planning_retries: -1
recovery_behaviors: 
  - name: conservative_reset
    type: clear_costmap_recovery/ClearCostmapRecovery

NavfnROS:
  allow_unknown: false
  default_tolerance: 5
  planner_window_x: 0
  planner_window_y: 0
  use_dijkstra: true
  use_quadratic: false
  use_grid_path: false
  cost_factor: 3.0
  neutral_cost: 77.0
  visualize_potential: false
  publish_potential: false

GlobalPlanner:
  allow_unknown: false
  default_tolerance: 5
  planner_window_x: 0
  planner_window_y: 0
  orientation_window_size: 2
  use_dijkstra: true
  use_quadratic: true
  use_grid_path: false
  orientation_mode: 2
  lethal_cost: 128
  cost_factor: 0.6
  neutral_cost: 55.0
  visualize_potential: false
  publish_potential: false
