publish_acceleration: true
print_diagnostics: true
two_d_mode: false
transform_time_offset: 0
transform_timeout: 0
sensor_timeout: 0.5
frequency: 50
imu0_config: [false, false, false,
              false, false, false,
              false, false, false,
              true, true, true,
              true, true, true]
odom0_config: [true, true, true,
               true, true, true,
               true , true, true,
               true, true, true,
               false, false, false]
