initial_pose_x: 0.0
initial_pose_y: 0.0
initial_pose_a: 0.0
odom_alpha1: 0.13
odom_alpha2: 0.15
odom_alpha3: 0.18
odom_alpha4: 0.12
kld_err: 0.06
recovery_alpha_slow: 0.001
recovery_alpha_fast: 0.1
resample_interval: 1
resample_interval: 2.0
update_min_d: 0.25
update_min_a: 0.0945
min_particles: 100
max_particles: 220
laser_model_type: likelihood_field_prob
odom_model_type: diff-corrected
use_map_topic: true
selective_resampling: true
tf_broadcast: true
transform_tolerance: 0.5
