acc_lpf_step: 128.0
acc_var: 0.785398
accum_cloud: 2
bias_var_ang: 1.57
bias_var_dist: 100.0
compatible: 1
dist_weight_x: 2.25
dist_weight_y: 2.25
dist_weight_z: 2.25
downsample_x: 0.19
downsample_y: 0.19
downsample_z: 0.05
expansion_var_pitch: 0.1
expansion_var_roll: 0.1
expansion_var_x: 0.2
expansion_var_y: 0.2
expansion_var_yaw: 0.03
expansion_var_z: 0.2
fix_ang: 0.3
fix_dist: 0.5
init_pitch: 0
init_roll: 0
init_var_pitch: 0.01
init_var_roll: 0.01
init_var_x: 2.0
init_var_y: 2.0
init_var_yaw: 0.5
init_var_z: 1.0
init_x: 0
init_y: 0
init_yaw: 0
init_z: 0
jump_ang: 0.67
jump_dist: 1.5
likelihood:
  clip_far: 100.0
  clip_near: 1.5
  match_dist_flat: 0.125
  match_dist_min: 0.85
  num_points: 128
  num_points_global: 30
lpf_step: 0.9
map_chunk: 10.0
map_downsample_x: 0.2
map_downsample_y: 0.2
map_downsample_z: 0.05
map_frame: map
match_output_dist: 0.9
match_output_interval_interval: 0.1
match_ratio_thresh: 0.78
num_particles: 192
odom_err_ang_ang: 0.35
odom_err_ang_lin: 0.05
odom_err_integ_ang_tc: 10.0
odom_err_integ_lin_sigma: 100.0
odom_err_integ_lin_tc: 10.0
odom_err_lin_ang: 0.15
odom_err_lin_lin: 0.7
output_pcd: false
publish_tf: true
resample_var_pitch: 0.021
resample_var_roll: 0.021
resample_var_x: 0.005
resample_var_y: 0.005
resample_var_yaw: 0.005
resample_var_z: 0.005
robot_frame: base_link
skip_measure: 1
tf_tolerance: 0.025
unmatch_output_dist: 0.5
update_downsample_x: 0.2
update_downsample_y: 0.2
update_downsample_z: 0.05

